# Generated by Django 5.2.7 on 2026-01-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_backend', '0002_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя'),
        ),
    ]
