# Generated by Django 5.2.7 on 2026-01-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_backend', '0003_call_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.IntegerField(choices=[(0, 'Открытый'), (1, 'Выполнен')], default=0, verbose_name='Статус'),
        ),
    ]
