# Generated by Django 5.2.7 on 2026-01-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_backend', '0004_call_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='visibility',
            new_name='is_visible',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
