# Generated by Django 5.2.7 on 2026-03-12 01:01

import clinic_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_backend', '0005_rename_visibility_procedure_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='confirm_token',
            field=models.CharField(default=clinic_backend.models.generate_hashed_confirm_token, max_length=64, null=True, unique=True, verbose_name='Токен подтверждения'),
        ),
    ]
