# Generated by Django 5.2.7 on 2026-03-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_backend', '0006_alter_booking_confirm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Телефон')),
                ('ads_consent', models.BooleanField(default=False, verbose_name='Согласие на рекламу')),
                ('ads_consent_given', models.DateTimeField(blank=True, null=True, verbose_name='Согласие дано')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
